### ISSUE TITLE
运行result_analysis.py的报错

### ISSUE THREAD

**Issue by timohaha** [WwZzz/easyFL#13]
`Traceback (most recent call last):
  File "D:/zyz/paper2/code/utils/result_analysis.py", line 505, in <module>
    drawer.draw(cfg['ploter'])
  File "D:/zyz/paper2/code/utils/result_analysis.py", line 251, in draw
    f(plot_obj)
  File "D:/zyz/paper2/code/utils/result_analysis.py", line 329, in bar
    data = [d[plot_obj['y']] for d in self.rec_dicts]
  File "D:/zyz/paper2/code/utils/result_analysis.py", line 329, in <listcomp>
    data = [d[plot_obj['y']] for d in self.rec_dicts]
KeyError: 'client_datavol'`

**Comment by WwZzz** [comment]
你好，错误来源于result_analysis文件的默认参数res_config.yml所指定的画图plot中，需要指定的y被Logger记录为同名的变量（例，所保存的logger.output字典中需要包含名称为client_datavol的键值对)。由于在后续对logger的更新中取消了对client_datavol进行默认保存，因此报错；现已将client_datavol从res_config.yml中删除并更新至github。谢谢你的反馈

**Comment by JTYSXYYYBFDLJZ** [comment]
你好，fmodule中
def zeros_like(self):
        return self*0
TypeError: unsupported operand type(s) for *
这个是想建立一个和模型一样的全零张量吗？

**Comment by Lyy838354973** [comment]
> 你好，错误来源于result_analysis文件的默认参数res_config.yml所指定的画图plot中，需要指定的y被Logger记录为同名的变量（例，所保存的logger.output字典中需要包含名称为client_datavol的键值对）。由于在后续对logger的更新中取消了对client_datavol进行默认保存，因此报错;现已将client_datavol从res_config.yml中删除并更新至GitHub。谢谢你的反馈

重新下载了最新版，还是有这个错误，请问怎么解决
