### ISSUE TITLE
你好，使用fedfa时报错

### ISSUE THREAD

**Issue by 0Regrets** [WwZzz/easyFL#16]
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    main()
  File "main.py", line 10, in main
    server = flw.initialize(option)
  File "D:\easyFL\utils\fflow.py", line 159, in initialize
    clients = [Client(option, name=client_names[cid], train_data=train_datas[cid], valid_data=valid_datas[cid]) for cid in range(num_clients)]
  File "D:\easyFL\utils\fflow.py", line 159, in <listcomp>
    clients = [Client(option, name=client_names[cid], train_data=train_datas[cid], valid_data=valid_datas[cid]) for cid in range(num_clients)]
  File "D:\easyFL\algorithm\fedfa.py", line 49, in __init__
    self.momentum = option ['gamma']
KeyError: 'gamma'

**Comment by WwZzz** [comment]
你好，错误原因是算法没有及时更新至最新版本。在Server构造函数中初始化Client的momentum后bug解决。最新的正确版本已测试并上传。

**Comment by 0Regrets** [comment]
非常感谢！
