### ISSUE TITLE
运行报错 ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by Ianshuan-wang** [WwZzz/easyFL#65]
我只是运行test部分的代码 报了如下错误：

Traceback (most recent call last):
  File "E:\wyx_projects\Pycharm\easyFL\test.py", line 1, in <module>
    import flgo.algorithm.fedavg as fedavg
  File "E:\wyx_projects\Pycharm\easyFL\flgo\__init__.py", line 1, in <module>
    from .utils.fflow import init, gen_task, gen_task_by_, gen_benchmark_from_file, gen_direct_task_from_file, zip_task, pull_task_from_, gen_real_task, gen_decentralized_benchmark, gen_hierarchical_benchmark, gen_empty_task, convert_model,tune, run_in_parallel, run_in_sequencial, module2fmodule, multi_init_and_run, multi_tune, tune_sequencially, set_data_root,download_resource, clear_task_cache, list_resource, option_helper
  File "E:\wyx_projects\Pycharm\easyFL\flgo\utils\fflow.py", line 47, in <module>
    import flgo.utils.shared_memory as fus
  File "E:\wyx_projects\Pycharm\easyFL\flgo\utils\shared_memory.py", line 2, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

请问这个bug如何解决呢？在网上搜索解决办法没有管用的

**Comment by WwZzz** [comment]
> 我只是运行test部分的代码 报了如下错误：
> 
> Traceback (most recent call last): File "E:\wyx_projects\Pycharm\easyFL\test.py", line 1, in import flgo.algorithm.fedavg as fedavg File "E:\wyx_projects\Pycharm\easyFL\flgo__init__.py", line 1, in from .utils.fflow import init, gen_task, gen_task_by_, gen_benchmark_from_file, gen_direct_task_from_file, zip_task, pull_task_from_, gen_real_task, gen_decentralized_benchmark, gen_hierarchical_benchmark, gen_empty_task, convert_model,tune, run_in_parallel, run_in_sequencial, module2fmodule, multi_init_and_run, multi_tune, tune_sequencially, set_data_root,download_resource, clear_task_cache, list_resource, option_helper File "E:\wyx_projects\Pycharm\easyFL\flgo\utils\fflow.py", line 47, in import flgo.utils.shared_memory as fus File "E:\wyx_projects\Pycharm\easyFL\flgo\utils\shared_memory.py", line 2, in import resource ModuleNotFoundError: No module named 'resource'
> 
> 请问这个bug如何解决呢？在网上搜索解决办法没有管用的

在新版中引入了对这个包的依赖。可以使用pip install resource手动安装
